---
title: "writing_functions.Rmd"
output: html_document
date: "2022-10-27"
---

```{r}
library(tidyverse)
library(rvest)
set.seed(1)
```

## z-scores
```{r}
x_vec = rnorm(25, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

```{r}
z_scores = function(x) {
  
  z = (x - mean(x)) / sd(x)
  z
  
}

z_scores(x_vec)
```

```{r eval=FALSE}
z_score = function(x) {
  
  if(is.numeric(x)){
    stop("Z scores only work for numbers")
  }

  if(length(x) < 3){
    stop("Z scores really only work if you have three or more numbers")
  }
  
  z = (x - mean(x)) / sd(x)
  z
  
}

z_score(x = 3)
z_score(x = "msu")
```

## get mean and sd from the vector input
```{r eval=FALSE}
x_vec = rnorm(25, mean = 5, sd = 3)

mean_and_sd = function(x){
  
  if(is.numeric(x)){
    stop("Z scores only work for numbers")
  }

  if(length(x) < 3){
    stop("Z scores really only work if you have three or more numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}

mean_and_sd(x = x_vec)
```

start with simulation

```{r eval=FALSE}
x_vec = rnorm(n = 2500, mean = 17, sd = 4)

tibble(
  mean = mean(x_vec)
  sd = sd(x_vec)
)
```


```{r}
sim_mean_sd = function(n_obs, true_mean = 7, true_sd = 4){
  
  x = rnorm(n = n_obs, mean = true_mean, sd = true_sd)
  
  tibble(
    mean = mean(x),
    sd = sd(x)
  )
  
}

sim_mean_sd(n_ob = 25, true_mean = 100, true_sd = 1)
sim_mean_sd(24)
sim_mean_sd(25, 100, 1)
```

## fixing bad stuff
```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

```{r}
read_page_reviews = function(url){
  
  html = read_html(url)

  review_titles = 
    dynamite_html %>%
    html_nodes(".a-text-bold span") %>%
    html_text()


review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim() %>% 
  str_subset("The media could not be loaded.", negate = TRUE) %>% 
  str_subset("^$", negate = TRUE)

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
  
}
```

```{r eval=FALSE}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"
  
read_page_reviews(url)
vec_url = str_c(base_url, c(1, 2, 3, 4))
dynamite_reviews = 
  bind_rows(
    read_page_reviews(vec_url[1])
    read_page_reviews(vec_url[2])
    read_page_reviews(vec_url[3])
    read_page_reviews(vec_url[4])
)

```


```{r}
x_vec = rnorm(25, 0, 1)

my_summary = function(x, summ_func) {
  summ_func(x)
}

my_summary(x_vec, sd)
```


